from __future__ import annotations

import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent


QUESTIONS = [
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代图书文物",
        "difficulty": 1,
        "stem": "目前已知中国境内较早的人类遗址之一、位于云南的是哪一项？",
        "options": ["元谋人", "蓝田人", "北京人", "山顶洞人"],
        "answer": "A",
        "explanation": "元谋人遗址位于云南元谋，是中国境内重要的早期人类遗址之一，常作为原始人群考点出现。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代衣食住行",
        "difficulty": 1,
        "stem": "北京人遗址位于北京周口店龙骨山，下列哪项最能体现北京人的生产生活特征？",
        "options": ["会使用和保存天然火", "已普遍使用铁器", "能够建造宫殿", "发明了活字印刷术"],
        "answer": "A",
        "explanation": "北京人会使用和保存天然火，这是原始人群部分的高频基础考点。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代经济发展",
        "difficulty": 1,
        "stem": "半坡文化位于黄河流域，其农业生产中较具代表性的作物是：",
        "options": ["粟", "水稻", "棉花", "玉米"],
        "answer": "A",
        "explanation": "半坡文化位于陕西西安一带，属于黄河流域，代表性农作物是粟。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代衣食住行",
        "difficulty": 1,
        "stem": "河姆渡文化位于长江流域，其建筑形式中常被提到的是：",
        "options": ["干栏式建筑", "窑洞式建筑", "四合院建筑", "台基式宫殿"],
        "answer": "A",
        "explanation": "河姆渡文化位于浙江余姚一带，常与水稻种植和干栏式建筑相联系。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代职官与科举",
        "difficulty": 1,
        "stem": "我国历史上第一个王朝通常被认为是：",
        "options": ["夏朝", "商朝", "西周", "秦朝"],
        "answer": "A",
        "explanation": "夏朝通常被视为我国历史上第一个王朝，也是世袭制取代禅让制的重要节点。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代图书文物",
        "difficulty": 1,
        "stem": "目前我们能够见到的较早的成熟汉字体系是：",
        "options": ["甲骨文", "小篆", "隶书", "楷书"],
        "answer": "A",
        "explanation": "甲骨文是商代刻写在龟甲兽骨上的文字，是目前能见到的较早成熟汉字体系。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 2,
        "stem": "秦统一六国后，作为官方统一文字推广的是：",
        "options": ["小篆", "甲骨文", "草书", "行书"],
        "answer": "A",
        "explanation": "秦朝统一文字，以小篆作为官方标准文字，同时隶书在民间逐渐流行。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代军事战争",
        "difficulty": 1,
        "stem": "中国历史上第一次大规模农民起义通常指的是：",
        "options": ["陈胜、吴广大泽乡起义", "黄巾起义", "绿林起义", "赤眉起义"],
        "answer": "A",
        "explanation": "秦末陈胜、吴广大泽乡起义是中国历史上第一次大规模农民起义。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代职官与科举",
        "difficulty": 2,
        "stem": "汉武帝采纳董仲舒建议后，思想文化政策的重要变化是：",
        "options": ["罢黜百家，独尊儒术", "焚书坑儒", "百家争鸣", "废除科举"],
        "answer": "A",
        "explanation": "汉武帝时期采纳董仲舒建议，确立“罢黜百家，独尊儒术”的文化政策。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代经济发展",
        "difficulty": 2,
        "stem": "汉代张骞出使西域，与下列哪一历史现象关系最密切？",
        "options": ["丝绸之路的开拓", "大运河的开凿", "科举制的创立", "三省六部制的形成"],
        "answer": "A",
        "explanation": "张骞出使西域被称为“凿空”，推动了丝绸之路的开拓与中西交流。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代军事战争",
        "difficulty": 2,
        "stem": "下列战役中，与“风声鹤唳、草木皆兵”成语相关的是：",
        "options": ["淝水之战", "官渡之战", "赤壁之战", "牧野之战"],
        "answer": "A",
        "explanation": "淝水之战中东晋以少胜前秦，相关典故包括“风声鹤唳”“草木皆兵”。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代职官与科举",
        "difficulty": 2,
        "stem": "隋炀帝设置进士科，标志着下列哪一制度正式形成？",
        "options": ["科举制度", "分封制度", "宗法制度", "井田制度"],
        "answer": "A",
        "explanation": "隋炀帝设进士科，通常被视为科举制度正式形成的重要标志。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代军事战争",
        "difficulty": 1,
        "stem": "唐朝由盛转衰的重要转折点是：",
        "options": ["安史之乱", "靖康之变", "陈桥兵变", "黄巾起义"],
        "answer": "A",
        "explanation": "安史之乱由安禄山、史思明发动，是唐朝由盛转衰的重要历史事件。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "古代军事战争",
        "difficulty": 2,
        "stem": "“陈桥兵变、黄袍加身”与下列哪位历史人物有关？",
        "options": ["赵匡胤", "李世民", "朱元璋", "忽必烈"],
        "answer": "A",
        "explanation": "赵匡胤通过陈桥兵变建立北宋，“黄袍加身”是相关典故。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "近现代史学常识",
        "difficulty": 2,
        "stem": "《马关条约》的签订与下列哪场战争直接相关？",
        "options": ["甲午中日战争", "鸦片战争", "第二次鸦片战争", "八国联军侵华战争"],
        "answer": "A",
        "explanation": "甲午中日战争后清政府与日本签订《马关条约》，中国半殖民地化程度进一步加深。",
    },
    {
        "category": "历史",
        "module": "中国历史学常识",
        "submodule": "近现代史学常识",
        "difficulty": 1,
        "stem": "辛亥革命中，标志清政府统治瓦解的重要起义是：",
        "options": ["武昌起义", "南昌起义", "秋收起义", "广州起义"],
        "answer": "A",
        "explanation": "1911年武昌起义爆发，推动辛亥革命发展并最终促成清王朝覆灭。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "文学总集",
        "difficulty": 1,
        "stem": "我国最早的一部诗歌总集是：",
        "options": ["《诗经》", "《楚辞》", "《文选》", "《乐府诗集》"],
        "answer": "A",
        "explanation": "《诗经》是我国最早的诗歌总集，分为风、雅、颂三部分。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 1,
        "stem": "《离骚》的作者是：",
        "options": ["屈原", "宋玉", "司马迁", "班固"],
        "answer": "A",
        "explanation": "《离骚》是屈原的代表作，也是楚辞文学的重要作品。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "文体流变",
        "difficulty": 2,
        "stem": "《左传》在史书体例上通常被归为：",
        "options": ["编年体史书", "纪传体通史", "国别体史书", "断代史"],
        "answer": "A",
        "explanation": "《左传》是解释《春秋》的编年体史书，按年代顺序记事。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 2,
        "stem": "我国第一部纪传体通史是：",
        "options": ["《史记》", "《汉书》", "《资治通鉴》", "《左传》"],
        "answer": "A",
        "explanation": "司马迁的《史记》是我国第一部纪传体通史，被誉为“史家之绝唱，无韵之离骚”。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "文体流变",
        "difficulty": 2,
        "stem": "汉代文学中，最能体现铺陈排比、辞藻华丽特征的文体是：",
        "options": ["赋", "词", "曲", "传奇"],
        "answer": "A",
        "explanation": "汉赋常以铺陈、夸饰、排比见长，是汉代文学的代表性文体。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "创作群体及文学流派",
        "difficulty": 2,
        "stem": "“三曹”通常指曹操、曹丕和哪一位？",
        "options": ["曹植", "曹叡", "曹爽", "曹休"],
        "answer": "A",
        "explanation": "建安文学中的“三曹”指曹操、曹丕、曹植，是魏晋文学的重要考点。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 1,
        "stem": "中国文学史上被称为“田园诗人”的代表人物是：",
        "options": ["陶渊明", "谢灵运", "王维", "孟浩然"],
        "answer": "A",
        "explanation": "陶渊明以田园诗著称，代表作有《归园田居》《桃花源记》等。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "创作群体及文学流派",
        "difficulty": 2,
        "stem": "下列哪位属于“初唐四杰”？",
        "options": ["王勃", "李白", "杜甫", "韩愈"],
        "answer": "A",
        "explanation": "初唐四杰指王勃、杨炯、卢照邻、骆宾王。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 1,
        "stem": "“诗仙”通常指的是：",
        "options": ["李白", "杜甫", "白居易", "王维"],
        "answer": "A",
        "explanation": "李白诗风浪漫豪放，被后世称为“诗仙”。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 1,
        "stem": "“诗圣”通常指的是：",
        "options": ["杜甫", "李白", "孟浩然", "岑参"],
        "answer": "A",
        "explanation": "杜甫诗歌深刻反映社会现实，被后世尊为“诗圣”。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "创作群体及文学流派",
        "difficulty": 2,
        "stem": "“唐宋八大家”中，唐代文学家不包括下列哪一位？",
        "options": ["苏轼", "韩愈", "柳宗元", "以上都不是"],
        "answer": "A",
        "explanation": "唐宋八大家中唐代有韩愈、柳宗元；苏轼是宋代文学家。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "创作群体及文学流派",
        "difficulty": 2,
        "stem": "宋词中，苏轼、辛弃疾通常被归入哪一词派？",
        "options": ["豪放派", "婉约派", "田园派", "边塞派"],
        "answer": "A",
        "explanation": "苏轼、辛弃疾是宋词豪放派代表人物；柳永、李清照常被归入婉约派。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 1,
        "stem": "元杂剧《窦娥冤》的作者是：",
        "options": ["关汉卿", "马致远", "王实甫", "白朴"],
        "answer": "A",
        "explanation": "关汉卿是元曲四大家之一，《窦娥冤》是其代表作。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 1,
        "stem": "下列作品中，不属于中国古典四大名著的是：",
        "options": ["《儒林外史》", "《红楼梦》", "《西游记》", "《三国演义》"],
        "answer": "A",
        "explanation": "中国古典四大名著为《三国演义》《水浒传》《西游记》《红楼梦》。",
    },
    {
        "category": "文学",
        "module": "中国文学常识",
        "submodule": "代表作家及作品",
        "difficulty": 2,
        "stem": "中国现代文学史上第一篇白话小说通常被认为是：",
        "options": ["《狂人日记》", "《阿Q正传》", "《药》", "《祝福》"],
        "answer": "A",
        "explanation": "鲁迅的《狂人日记》通常被认为是中国现代文学史上第一篇白话小说。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 1,
        "stem": "二十四节气中，通常标志春季开始的是：",
        "options": ["立春", "春分", "谷雨", "惊蛰"],
        "answer": "A",
        "explanation": "立春是二十四节气之首，通常表示春季开始。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 2,
        "stem": "下列节气中，同时也常作为传统节日被人们熟知的是：",
        "options": ["清明", "小满", "芒种", "白露"],
        "answer": "A",
        "explanation": "清明既是二十四节气之一，也是重要的传统节日，兼具祭扫、踏青等习俗。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 2,
        "stem": "古代夜间“五更”计时中，“三更”大致对应的是：",
        "options": ["子时", "丑时", "寅时", "亥时"],
        "answer": "A",
        "explanation": "五更中一更约戌时，二更约亥时，三更约子时，四更约丑时，五更约寅时。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 2,
        "stem": "干支纪年中，天干地支组合一个完整循环共有多少年？",
        "options": ["60年", "12年", "24年", "100年"],
        "answer": "A",
        "explanation": "十天干与十二地支依次相配，最小公倍数为60，因此形成六十年一循环。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 1,
        "stem": "端午节的传统纪念对象，民间最常见的说法是：",
        "options": ["屈原", "介子推", "伍子胥", "曹娥"],
        "answer": "A",
        "explanation": "端午节习俗来源较多，但考试中最常见的说法是纪念屈原。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 1,
        "stem": "重阳节的传统习俗之一是：",
        "options": ["登高", "守岁", "赛龙舟", "吃元宵"],
        "answer": "A",
        "explanation": "重阳节在农历九月初九，常见习俗包括登高、赏菊、佩茱萸等。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 2,
        "stem": "寒食节的传说通常与下列哪位人物有关？",
        "options": ["介子推", "屈原", "范蠡", "苏武"],
        "answer": "A",
        "explanation": "寒食节传说与春秋时期晋国介子推有关，常与禁火冷食习俗相连。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 2,
        "stem": "古代兄弟排行常用“伯、仲、叔、季”表示，其中“仲”通常表示：",
        "options": ["排行第二", "排行第一", "排行第三", "排行最末"],
        "answer": "A",
        "explanation": "伯、仲、叔、季分别常用于表示长、次、三、幼等排行关系。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代礼俗与称谓",
        "difficulty": 1,
        "stem": "“花甲之年”通常指多少岁？",
        "options": ["60岁", "50岁", "70岁", "80岁"],
        "answer": "A",
        "explanation": "花甲源于干支六十年一循环，因此“花甲之年”通常指60岁。",
    },
    {
        "category": "传统文化",
        "module": "中国历史学常识",
        "submodule": "古代职官与科举",
        "difficulty": 2,
        "stem": "科举考试中，通过乡试者通常称为：",
        "options": ["举人", "秀才", "进士", "状元"],
        "answer": "A",
        "explanation": "明清科举中，乡试合格者称举人；会试、殿试之后才涉及进士、状元等称谓。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "书法",
        "difficulty": 1,
        "stem": "秦统一文字时采用的标准字体是：",
        "options": ["小篆", "楷书", "草书", "行书"],
        "answer": "A",
        "explanation": "秦朝统一文字，官方标准字体为小篆，这是书法与历史交叉高频考点。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "书法",
        "difficulty": 2,
        "stem": "被后世尊称为“书圣”的书法家是：",
        "options": ["王羲之", "颜真卿", "柳公权", "赵孟頫"],
        "answer": "A",
        "explanation": "王羲之被誉为“书圣”，代表作《兰亭集序》在书法史上地位极高。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "绘画",
        "difficulty": 2,
        "stem": "东晋画家顾恺之的代表作之一是：",
        "options": ["《洛神赋图》", "《清明上河图》", "《富春山居图》", "《游春图》"],
        "answer": "A",
        "explanation": "顾恺之是东晋著名画家，《洛神赋图》是其重要代表作品。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "绘画",
        "difficulty": 1,
        "stem": "唐代画家吴道子被后世称为：",
        "options": ["画圣", "书圣", "诗圣", "医圣"],
        "answer": "A",
        "explanation": "吴道子是唐代著名画家，被后世尊为“画圣”。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "绘画",
        "difficulty": 1,
        "stem": "《清明上河图》的作者是：",
        "options": ["张择端", "顾恺之", "阎立本", "赵孟頫"],
        "answer": "A",
        "explanation": "《清明上河图》是北宋画家张择端的传世名作，表现北宋城市生活景象。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "绘画",
        "difficulty": 2,
        "stem": "中国画传统题材中，通常不属于主要分类的是：",
        "options": ["静物画", "人物画", "山水画", "花鸟画"],
        "answer": "A",
        "explanation": "中国画常见传统分类包括人物、山水、花鸟等，“静物画”更多见于西方绘画分类。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "雕塑",
        "difficulty": 1,
        "stem": "秦始皇陵兵马俑主要属于下列哪类艺术遗存？",
        "options": ["雕塑", "书法", "戏曲", "音乐"],
        "answer": "A",
        "explanation": "秦始皇陵兵马俑是中国古代雕塑艺术和秦代丧葬制度的重要实物资料。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "雕塑",
        "difficulty": 2,
        "stem": "敦煌莫高窟最能集中体现的艺术类型是：",
        "options": ["壁画与佛教造像", "青铜铸造", "园林建筑", "水墨山水"],
        "answer": "A",
        "explanation": "莫高窟以大量佛教壁画和彩塑著称，是中国石窟艺术的重要代表。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "戏剧",
        "difficulty": 2,
        "stem": "被誉为“百戏之祖”的中国传统戏曲剧种是：",
        "options": ["昆曲", "京剧", "越剧", "豫剧"],
        "answer": "A",
        "explanation": "昆曲历史悠久，艺术体系成熟，被称为“百戏之祖”。",
    },
    {
        "category": "艺术",
        "module": "中国艺术常识",
        "submodule": "建筑",
        "difficulty": 2,
        "stem": "中国古代木构建筑中常见的“斗拱”主要作用之一是：",
        "options": ["承托屋檐并分散受力", "记录天文历法", "制作陶瓷纹样", "表示官职等级"],
        "answer": "A",
        "explanation": "斗拱是中国古代木构建筑的重要构件，具有承托屋檐、传递和分散荷载等作用。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "科技发明",
        "difficulty": 1,
        "stem": "下列不属于中国古代四大发明的是：",
        "options": ["地动仪", "造纸术", "指南针", "火药"],
        "answer": "A",
        "explanation": "中国古代四大发明通常指造纸术、印刷术、指南针、火药；地动仪是重要科技成就但不属四大发明。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "科技发明",
        "difficulty": 1,
        "stem": "东汉时期改进造纸术、推动纸张普及的人物是：",
        "options": ["蔡伦", "张衡", "祖冲之", "毕昇"],
        "answer": "A",
        "explanation": "蔡伦改进造纸术，使纸张质量和生产效率提高，对文化传播影响深远。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "科技发明",
        "difficulty": 1,
        "stem": "北宋时期发明活字印刷术的人物是：",
        "options": ["毕昇", "沈括", "郭守敬", "徐光启"],
        "answer": "A",
        "explanation": "毕昇发明泥活字印刷术，沈括在《梦溪笔谈》中记载了这一发明。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "科技发明",
        "difficulty": 2,
        "stem": "指南针在古代对世界文明交流影响最大的领域是：",
        "options": ["航海活动", "农业灌溉", "陶瓷烧制", "医学诊断"],
        "answer": "A",
        "explanation": "指南针应用于航海后，显著推动远洋航行和世界文明交流。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "天文历法与算学",
        "difficulty": 2,
        "stem": "中国古代数学名著《九章算术》主要体现的是哪一领域的成就？",
        "options": ["数学", "医学", "地理", "农学"],
        "answer": "A",
        "explanation": "《九章算术》是中国古代重要数学著作，集中体现古代实用数学成就。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "天文历法与算学",
        "difficulty": 2,
        "stem": "把圆周率计算到小数点后第七位的南北朝数学家是：",
        "options": ["祖冲之", "刘徽", "张衡", "郭守敬"],
        "answer": "A",
        "explanation": "祖冲之将圆周率精确到小数点后第七位，是中国古代数学史的重要成就。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "天文历法与算学",
        "difficulty": 2,
        "stem": "东汉科学家张衡的重要发明之一是：",
        "options": ["候风地动仪", "活字印刷术", "火药武器", "水排"],
        "answer": "A",
        "explanation": "张衡发明候风地动仪，用于探测地震方向，是古代科技重要成果。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "医学",
        "difficulty": 1,
        "stem": "明代医药学家李时珍编写的药物学巨著是：",
        "options": ["《本草纲目》", "《伤寒杂病论》", "《黄帝内经》", "《千金方》"],
        "answer": "A",
        "explanation": "李时珍编写《本草纲目》，系统总结中国古代药物学成就。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "医学",
        "difficulty": 2,
        "stem": "被后世尊称为“医圣”的东汉医学家是：",
        "options": ["张仲景", "华佗", "孙思邈", "李时珍"],
        "answer": "A",
        "explanation": "张仲景著有《伤寒杂病论》，被后世尊称为“医圣”。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "农业水利",
        "difficulty": 2,
        "stem": "明代徐光启编写、系统总结农业生产经验的著作是：",
        "options": ["《农政全书》", "《齐民要术》", "《天工开物》", "《梦溪笔谈》"],
        "answer": "A",
        "explanation": "徐光启的《农政全书》系统总结农业生产经验，是明代重要农学著作。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "科技发明",
        "difficulty": 2,
        "stem": "《梦溪笔谈》的作者是：",
        "options": ["沈括", "郭守敬", "宋应星", "徐光启"],
        "answer": "A",
        "explanation": "《梦溪笔谈》是北宋沈括所著，内容涉及自然科学、技术、历史文化等多个方面。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "农业水利",
        "difficulty": 1,
        "stem": "战国时期由李冰主持修建、至今仍发挥作用的大型水利工程是：",
        "options": ["都江堰", "郑国渠", "灵渠", "京杭大运河"],
        "answer": "A",
        "explanation": "都江堰由战国时期秦国蜀郡太守李冰主持修建，是著名水利工程。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "地理舆图",
        "difficulty": 3,
        "stem": "提出“制图六体”、被称为中国科学制图学之父的人物是：",
        "options": ["裴秀", "郦道元", "徐霞客", "沈括"],
        "answer": "A",
        "explanation": "裴秀提出“制图六体”，对中国古代地图学发展影响很大。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "天文历法与算学",
        "difficulty": 3,
        "stem": "元代郭守敬主持修订、在历法精度上具有重要地位的是：",
        "options": ["《授时历》", "《太初历》", "《大衍历》", "《夏小正》"],
        "answer": "A",
        "explanation": "郭守敬主持制定《授时历》，是中国古代历法史上的重要成果。",
    },
    {
        "category": "科技",
        "module": "中国古代科技常识",
        "submodule": "科技发明",
        "difficulty": 3,
        "stem": "明代宋应星的《天工开物》主要记录的是：",
        "options": ["农业与手工业生产技术", "诗词格律", "军事兵法", "佛教经典"],
        "answer": "A",
        "explanation": "《天工开物》系统记录明代农业、手工业等生产技术，被誉为中国古代科技百科式著作。",
    },
]


ANSWER_KEYS = ["A", "B", "C", "D"]


def difficulty_label(value: int) -> str:
    return {1: "基础", 2: "中级", 3: "高级"}.get(value, "中级")


def to_user_format(question: dict) -> dict:
    return {
        "exam_code": "Z001",
        "subject": "中华文化",
        "category": question["category"],
        "module": question["module"],
        "submodule": question["submodule"],
        "difficulty": difficulty_label(question["difficulty"]),
        "question": question["stem"],
        "options": dict(zip(ANSWER_KEYS, question["options"])),
        "correct_answer": question["answer"],
        "explanation": question["explanation"],
    }


def to_import_format(question: dict) -> dict:
    return {
        "exam_code": "Z001",
        "subject": "中华文化",
        "module": question["module"],
        "submodule": question["submodule"],
        "question_type": "single_choice",
        "stem": question["stem"],
        "option_a": question["options"][0],
        "option_b": question["options"][1],
        "option_c": question["options"][2],
        "option_d": question["options"][3],
        "answer": question["answer"],
        "explanation": question["explanation"],
        "difficulty": question["difficulty"],
        "source_type": "source_extracted",
        "source_year": 2026,
        "passage_id": None,
    }


def main() -> int:
    user_payload = {
        "source_document": "5、文化素养重点知识（必背100考点）.pdf",
        "description": "基于文化素养必背100考点生成的中华文化单选题，覆盖历史、文学、传统文化、艺术、科技成就。",
        "total": len(QUESTIONS),
        "questions": [to_user_format(question) for question in QUESTIONS],
    }
    import_payload = {"questions": [to_import_format(question) for question in QUESTIONS]}

    user_path = PROJECT_ROOT / "data" / "culture_literacy_100_key_points_questions_66.json"
    import_path = PROJECT_ROOT / "data" / "z001_culture_literacy_100_key_points_batch_001.json"

    user_path.write_text(json.dumps(user_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    import_path.write_text(json.dumps(import_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Wrote {len(QUESTIONS)} user-format questions to {user_path}")
    print(f"Wrote {len(QUESTIONS)} import-format questions to {import_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
