from __future__ import annotations

import json
import random
import re
from collections import Counter
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = PROJECT_ROOT / "data" / "common_english_language_knowledge_batch_003_traps_large.json"
REVIEW_PATH = PROJECT_ROOT / "data" / "common_english_language_knowledge_batch_003_traps_large_review.md"


def normalize_stem(value: str) -> str:
    return re.sub(r"\s+", "", value or "").strip().lower()


def load_existing_stems() -> set[str]:
    stems: set[str] = set()
    for path in (PROJECT_ROOT / "data").glob("*.json"):
        if path.resolve() == OUTPUT_PATH.resolve():
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        questions = payload.get("questions") if isinstance(payload, dict) else payload
        if not isinstance(questions, list):
            continue
        for item in questions:
            if isinstance(item, dict) and isinstance(item.get("stem"), str):
                stems.add(normalize_stem(item["stem"]))
    return stems


def make_options(correct: str, distractors: list[str], rng: random.Random) -> tuple[dict[str, str], str]:
    values: list[str] = []
    for value in [correct, *distractors]:
        if value and value not in values:
            values.append(value)
    if len(values) != 4:
        raise ValueError(f"Expected 4 unique options, got {values}")
    rng.shuffle(values)
    labels = ["A", "B", "C", "D"]
    options = dict(zip(labels, values))
    answer = next(label for label, value in options.items() if value == correct)
    return options, answer


def explanation_for(spec: dict, answer: str) -> str:
    return (
        f"本题考查英语运用中的“{spec['submodule']}”。正确答案为 {answer}（{spec['correct']}）。"
        f"{spec['reason']}"
        f"本题陷阱：{spec['trap']}"
        "解题时不要只看中文意思，要检查固定搭配、词性、语法结构和上下文逻辑是否同时成立。"
    )


def build_question(spec: dict, rng: random.Random) -> dict:
    options, answer = make_options(spec["correct"], spec["distractors"], rng)
    return {
        "exam_code": "COMMON",
        "subject": "英语运用",
        "module": "语言知识",
        "submodule": spec["submodule"],
        "question_type": "single_choice",
        "stem": spec["stem"],
        "option_a": options["A"],
        "option_b": options["B"],
        "option_c": options["C"],
        "option_d": options["D"],
        "answer": answer,
        "explanation": explanation_for(spec, answer),
        "difficulty": spec["difficulty"],
        "source_type": "ai_generated",
        "source_year": 2026,
        "passage_id": None,
    }


SPECS = [
    {
        "submodule": "词汇",
        "stem": "The findings are likely to have a significant ______ on future policy.",
        "correct": "impact",
        "distractors": ["impulse", "impression", "incident"],
        "reason": "have an impact on 是固定搭配，表示“对……产生影响”。",
        "trap": "impression 也有“印象、影响感”的含义，但不能构成 have an impression on future policy 的政策影响表达。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The committee was asked to ______ whether the data were reliable.",
        "correct": "determine",
        "distractors": ["define", "defend", "decline"],
        "reason": "determine whether... 表示“确定是否……”。",
        "trap": "define 是“下定义”，看似学术化，但不能表达判断数据是否可靠。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The new rules are intended to ______ cheating in online examinations.",
        "correct": "discourage",
        "distractors": ["discharge", "discover", "disturb"],
        "reason": "discourage doing sth. 表示“阻止、劝阻某事”。",
        "trap": "discharge 形近但表示“释放、解雇、排出”，语义完全不符。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The article ______ the importance of careful reading.",
        "correct": "emphasizes",
        "distractors": ["embarrasses", "enlarges", "emerges"],
        "reason": "emphasize the importance of... 表示“强调……的重要性”。",
        "trap": "emerges 形近且常见，但它是不及物动词，不能直接接 importance。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The patient showed a gradual ______ after receiving treatment.",
        "correct": "improvement",
        "distractors": ["approval", "movement", "employment"],
        "reason": "show improvement 表示“出现好转”。",
        "trap": "movement 有“移动、运动”的意思，但不能表达病情好转。",
        "difficulty": 2,
    },
    {
        "submodule": "词汇",
        "stem": "The explanation was so ______ that many students misunderstood the question.",
        "correct": "vague",
        "distractors": ["vivid", "valid", "violent"],
        "reason": "vague 表示“模糊的、不明确的”，会导致误解。",
        "trap": "valid 表示“有效的、有根据的”，形容解释时语义方向相反。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The research was ______ by a lack of reliable data.",
        "correct": "limited",
        "distractors": ["liberated", "located", "listed"],
        "reason": "be limited by 表示“受到……限制”。",
        "trap": "liberated 与 limited 形近但表示“解放的”，和语境相反。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The teacher asked us to give ______ examples rather than general statements.",
        "correct": "specific",
        "distractors": ["special", "spiritual", "separate"],
        "reason": "specific examples 表示“具体例子”。",
        "trap": "special 表示“特殊的”，中文上容易混淆，但不等于具体。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The old machine is still ______, though it is not very efficient.",
        "correct": "functional",
        "distractors": ["fashionable", "fictional", "fundamental"],
        "reason": "functional 表示“能运转的、有功能的”。",
        "trap": "fundamental 表示“基本的”，看似褒义但不表达机器还能用。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The evidence was not strong enough to ______ his argument.",
        "correct": "support",
        "distractors": ["supply", "survive", "suppose"],
        "reason": "support an argument 表示“支持论点”。",
        "trap": "supply 是“提供”，不能与 argument 构成“支持论点”的表达。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The plan sounds attractive, but it is not ______ in practice.",
        "correct": "feasible",
        "distractors": ["flexible", "faithful", "favorable"],
        "reason": "feasible 表示“可行的”，与 in practice 搭配自然。",
        "trap": "favorable 表示“有利的/赞成的”，不能表达实践可行性。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The professor's comments were ______ to the student's research topic.",
        "correct": "relevant",
        "distractors": ["relative", "reliable", "reluctant"],
        "reason": "be relevant to 表示“与……相关”。",
        "trap": "relative 可表示“相对的/亲戚”，但不能替代 relevant to。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The new evidence helped to ______ the suspect's innocence.",
        "correct": "establish",
        "distractors": ["estimate", "extend", "expose"],
        "reason": "establish innocence 表示“证明清白”。",
        "trap": "estimate 是“估计”，形式接近但不能表示证明事实。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The school has decided to ______ a new policy on mobile phone use.",
        "correct": "implement",
        "distractors": ["imply", "import", "imitate"],
        "reason": "implement a policy 表示“实施政策”。",
        "trap": "imply 是“暗示”，不能与 policy 构成执行意义。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The two words are similar in spelling but ______ in meaning.",
        "correct": "different",
        "distractors": ["difficult", "definite", "defensive"],
        "reason": "be different in meaning 表示“意义不同”。",
        "trap": "difficult 形近且常见，但表示“困难的”，不能说明意义差异。",
        "difficulty": 2,
    },
    {
        "submodule": "词汇",
        "stem": "The public library provides free ______ to digital resources.",
        "correct": "access",
        "distractors": ["excess", "assess", "asset"],
        "reason": "access to resources 表示“使用资源的机会/入口”。",
        "trap": "assess 是动词“评估”，excess 是“过量”，都是形近陷阱。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The new training program aims to ______ students' confidence.",
        "correct": "boost",
        "distractors": ["boast", "burst", "bind"],
        "reason": "boost confidence 表示“增强信心”。",
        "trap": "boast 是“夸耀”，和 boost 形近但语义不同。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The conclusion is based on several ______ assumptions.",
        "correct": "questionable",
        "distractors": ["questioning", "questioned", "questionnaire"],
        "reason": "questionable assumptions 表示“有疑问的假设”。",
        "trap": "questioning 是“提问的/质疑的”，不能自然修饰 assumptions 表示可靠性差。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The medicine had an immediate ______ on the patient's pain.",
        "correct": "effect",
        "distractors": ["affect", "effort", "offer"],
        "reason": "have an effect on 表示“对……产生影响”。",
        "trap": "affect 是动词，不能放在 an immediate 后作名词。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The government plans to ______ public spending next year.",
        "correct": "reduce",
        "distractors": ["deduce", "induce", "produce"],
        "reason": "reduce spending 表示“减少支出”。",
        "trap": "deduce 是“推断”，produce 是“生产”，均与 spending 不搭。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The speaker tried to make the complex idea more ______ to ordinary readers.",
        "correct": "accessible",
        "distractors": ["acceptable", "available", "accurate"],
        "reason": "accessible to readers 表示“读者容易理解/接触到”。",
        "trap": "acceptable 是“可接受的”，available 是“可获得的”，都不能准确表达“易懂”。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The two studies produced ______ results, so further research is needed.",
        "correct": "conflicting",
        "distractors": ["confident", "confirmed", "convenient"],
        "reason": "conflicting results 表示“相互矛盾的结果”。",
        "trap": "confirmed 表示“已证实的”，与后文需要进一步研究的逻辑不符。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The company promised to ______ customers for the delay.",
        "correct": "compensate",
        "distractors": ["compete", "compare", "compose"],
        "reason": "compensate sb. for sth. 表示“因某事补偿某人”。",
        "trap": "compete/compare 形近，但介词和语义都不符合 customers for the delay。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The students were asked to ______ the main idea of the passage in one sentence.",
        "correct": "summarize",
        "distractors": ["submit", "suggest", "suppose"],
        "reason": "summarize the main idea 表示“概括主旨”。",
        "trap": "submit 是“提交”，和 main idea 搭配不成立。",
        "difficulty": 2,
    },
    {
        "submodule": "词汇",
        "stem": "The results of the experiment were ______ with the researcher's expectations.",
        "correct": "consistent",
        "distractors": ["constant", "conscious", "considerable"],
        "reason": "be consistent with 表示“与……一致”。",
        "trap": "constant 表示“不变的”，看起来像“稳定”，但不能表达一致性。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "Students should learn to ______ reliable sources from unreliable ones.",
        "correct": "distinguish",
        "distractors": ["disappear", "distribute", "display"],
        "reason": "distinguish A from B 表示“把 A 与 B 区分开”。",
        "trap": "distribute 是“分配”，虽然也可接名词，但不能接 from unreliable ones 表达区分。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The mayor's speech ______ mainly on environmental protection.",
        "correct": "focused",
        "distractors": ["fixed", "founded", "forced"],
        "reason": "focus on 表示“集中于、关注”。",
        "trap": "fixed on 可表示“盯着”，但 speech fixed on 不自然。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The workers objected ______ the sudden change in their schedule.",
        "correct": "to",
        "distractors": ["against", "for", "with"],
        "reason": "object to sth./doing sth. 是固定搭配。",
        "trap": "中文“反对”容易联想到 against，但 object 作动词时固定接 to。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The result was ______ from what we had expected.",
        "correct": "different",
        "distractors": ["differ", "difference", "differently"],
        "reason": "be different from 是固定搭配。",
        "trap": "differ 是动词，difference 是名词，不能放在 was 后作表语形容词。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The school is ______ for the safety of all students during the trip.",
        "correct": "responsible",
        "distractors": ["responsive", "respectful", "respective"],
        "reason": "be responsible for 表示“对……负责”。",
        "trap": "responsive 表示“反应快的”，respective 表示“各自的”，都是形近词陷阱。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The student apologized ______ being late for class.",
        "correct": "for",
        "distractors": ["to", "with", "at"],
        "reason": "apologize for doing sth. 表示“因做某事道歉”。",
        "trap": "apologize to sb. 是向某人道歉，本句后接 being late，应使用 for。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The result may vary ______ person to person.",
        "correct": "from",
        "distractors": ["with", "between", "among"],
        "reason": "vary from person to person 是固定搭配。",
        "trap": "between/among 看似和人群有关，但不符合 from...to...结构。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The new policy applies ______ all full-time students.",
        "correct": "to",
        "distractors": ["for", "with", "at"],
        "reason": "apply to sb./sth. 表示“适用于……”。",
        "trap": "apply for 表示“申请”，语义完全不同。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The organization is committed ______ protecting children's rights.",
        "correct": "to",
        "distractors": ["for", "with", "on"],
        "reason": "be committed to doing sth. 表示“致力于做某事”。",
        "trap": "to 在这里是介词，后接 doing；不能按不定式思路改成动词原形。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The shortage of water resulted ______ a poor harvest.",
        "correct": "in",
        "distractors": ["from", "with", "by"],
        "reason": "result in 表示“导致”。",
        "trap": "result from 表示“由……造成”，方向正好相反。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The poor harvest resulted ______ the shortage of water.",
        "correct": "from",
        "distractors": ["in", "with", "by"],
        "reason": "result from 表示“由……造成”。",
        "trap": "result in 表示“导致”，因果方向与本句相反。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The success of the event depends ______ careful preparation.",
        "correct": "on",
        "distractors": ["of", "for", "with"],
        "reason": "depend on sth. 表示“取决于……”。",
        "trap": "for 可表示目的或原因，但 depend 固定接 on。",
        "difficulty": 2,
    },
    {
        "submodule": "词汇",
        "stem": "The young writer is known ______ his clear and simple style.",
        "correct": "for",
        "distractors": ["as", "to", "by"],
        "reason": "be known for 表示“因……而出名”。",
        "trap": "be known as 表示“作为……而出名”，后面通常接身份称谓，不接风格特点。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The young writer is known ______ a careful observer of city life.",
        "correct": "as",
        "distractors": ["for", "to", "with"],
        "reason": "be known as 表示“作为……而出名”，后接身份或称谓。",
        "trap": "be known for 后接出名的原因或特点，本句后面是身份。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The teacher insisted ______ checking every answer carefully.",
        "correct": "on",
        "distractors": ["to", "for", "with"],
        "reason": "insist on doing sth. 表示“坚持做某事”。",
        "trap": "insist 后可以接 that 从句，但接动名词时固定用 on。",
        "difficulty": 4,
    },
    {
        "submodule": "词汇",
        "stem": "The article refers ______ several recent studies on learning habits.",
        "correct": "to",
        "distractors": ["with", "about", "for"],
        "reason": "refer to 表示“提到、涉及”。",
        "trap": "about 在中文“关于”里很常见，但 refer 固定接 to。",
        "difficulty": 3,
    },
    {
        "submodule": "词汇",
        "stem": "The candidate failed to live ______ to the expectations of his supporters.",
        "correct": "up",
        "distractors": ["out", "on", "in"],
        "reason": "live up to expectations 表示“不辜负期望”。",
        "trap": "live on 是“靠……生活”，live in 是“居住在”，不能接 expectations 表示达到期望。",
        "difficulty": 5,
    },
    {
        "submodule": "词汇",
        "stem": "The university provides students ______ access to online journals.",
        "correct": "with",
        "distractors": ["for", "to", "by"],
        "reason": "provide sb. with sth. 表示“向某人提供某物”。",
        "trap": "provide sth. for sb. 也正确，但本句结构是 provide students with access。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "Neither the explanation nor the examples ______ clear enough.",
        "correct": "are",
        "distractors": ["is", "was", "has been"],
        "reason": "neither...nor...连接主语时，谓语通常遵循就近原则，examples 为复数。",
        "trap": "explanation 是单数且在前，容易误选 is。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "Not only the students but also the teacher ______ interested in the topic.",
        "correct": "is",
        "distractors": ["are", "were", "have been"],
        "reason": "not only...but also...连接主语时遵循就近原则，teacher 为单数。",
        "trap": "students 复数在前，容易诱导选择 are。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "Either the manager or the assistants ______ responsible for the mistake.",
        "correct": "are",
        "distractors": ["is", "was", "has been"],
        "reason": "either...or...连接主语时遵循就近原则，assistants 为复数。",
        "trap": "manager 是单数但离谓语较远，不决定谓语形式。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "Every student and every teacher ______ required to attend the meeting.",
        "correct": "is",
        "distractors": ["are", "were", "have been"],
        "reason": "every...and every...强调整体中的每一个个体，谓语用单数。",
        "trap": "and 连接两个名词，容易误判为复数主语。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "Ten years ______ a long time for a young researcher.",
        "correct": "is",
        "distractors": ["are", "were", "have been"],
        "reason": "表示时间、距离、金额等整体概念时，谓语常用单数。",
        "trap": "years 是复数形式，但这里表示一个整体时间段。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "The number of errors in the report ______ reduced after revision.",
        "correct": "was",
        "distractors": ["were", "are", "have"],
        "reason": "the number of...作主语时，中心词是 number，谓语用单数。",
        "trap": "errors 是复数，容易诱导选择 were。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "A number of useful suggestions ______ made during the discussion.",
        "correct": "were",
        "distractors": ["was", "is", "has"],
        "reason": "a number of 表示“许多”，后接复数名词，谓语用复数。",
        "trap": "the number of 和 a number of 形式相近但谓语规则相反。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "By next June, she ______ at this school for three years.",
        "correct": "will have studied",
        "distractors": ["will study", "has studied", "studied"],
        "reason": "by next June 表示将来某时间前已经完成，应用将来完成时。",
        "trap": "has studied 是现在完成时，不能对应 next June 这个将来时间。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "When I arrived at the station, the train ______.",
        "correct": "had left",
        "distractors": ["left", "has left", "was leaving"],
        "reason": "火车离开发生在我到达之前，过去的过去用过去完成时。",
        "trap": "left 只是一般过去，不能清楚表达先后关系。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "I will call you as soon as I ______ the result.",
        "correct": "get",
        "distractors": ["will get", "got", "have got"],
        "reason": "时间状语从句中用一般现在时表示将来。",
        "trap": "as soon as 后不能用 will get 表示普通将来。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "The letter ______ yesterday has already been replied to.",
        "correct": "received",
        "distractors": ["receiving", "to receive", "receives"],
        "reason": "letter 与 receive 是被动关系，过去分词 received 作后置定语。",
        "trap": "receiving 表主动，不能修饰被收到的信。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The man ______ at the gate is our new English teacher.",
        "correct": "standing",
        "distractors": ["stood", "to stand", "stand"],
        "reason": "man 与 stand 是主动关系，现在分词 standing 作后置定语。",
        "trap": "stood 是过去式/过去分词，不能表达正在站着的主动状态。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "The problem ______ at the meeting yesterday remains unsolved.",
        "correct": "discussed",
        "distractors": ["discussing", "to discuss", "discusses"],
        "reason": "problem 与 discuss 是被动关系，过去分词 discussed 作后置定语。",
        "trap": "discussing 表主动，问题不能主动讨论自己。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "With all the work ______, they went home early.",
        "correct": "finished",
        "distractors": ["finishing", "to finish", "finish"],
        "reason": "with + 宾语 + 过去分词表示宾语与动作之间为被动完成关系。",
        "trap": "finishing 表主动进行，work 不能主动完成自己。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "With the exam ______, the students felt more nervous.",
        "correct": "approaching",
        "distractors": ["approached", "to approach", "approach"],
        "reason": "exam 与 approach 在此为主动关系，表示考试临近，用现在分词。",
        "trap": "approached 表被动或完成，但考试不是被靠近的对象。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "I found it difficult ______ the difference between the two words.",
        "correct": "to explain",
        "distractors": ["explaining", "explained", "explain"],
        "reason": "find it + adj. + to do 是常用结构，it 作形式宾语。",
        "trap": "explaining 可作动名词，但在 find it difficult 后应使用不定式。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The teacher made the students ______ the passage again.",
        "correct": "read",
        "distractors": ["to read", "reading", "readed"],
        "reason": "make sb. do sth. 主动语态中宾补用动词原形。",
        "trap": "to read 受中文“让某人去做”影响容易误选，但 make 后省 to。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "The students were made ______ the passage again.",
        "correct": "to read",
        "distractors": ["read", "reading", "readed"],
        "reason": "make 用于被动语态时，省略的 to 要还原。",
        "trap": "主动 make sb. do 中不用 to，但被动 be made to do 必须加 to。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "It is high time that we ______ action to protect the environment.",
        "correct": "took",
        "distractors": ["take", "will take", "have taken"],
        "reason": "It is high time that... 后从句常用一般过去时表示“早该做”。",
        "trap": "we 是复数且语义指现在，但该固定句型要求过去式。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "I wish I ______ more attention to English grammar before.",
        "correct": "had paid",
        "distractors": ["paid", "have paid", "would pay"],
        "reason": "wish 表示对过去的遗憾时，从句用过去完成时。",
        "trap": "before 提示过去，但 wish 的过去遗憾要用 had done，不是一般过去。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "If only I ______ the answer during the test yesterday.",
        "correct": "had known",
        "distractors": ["knew", "have known", "would know"],
        "reason": "If only 表示对过去的遗憾时，用过去完成时。",
        "trap": "yesterday 容易诱导 knew，但虚拟语气要求 had known。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "The suggestion that the meeting ______ postponed was accepted.",
        "correct": "be",
        "distractors": ["was", "is", "has been"],
        "reason": "suggestion 后的同位语从句表示建议内容，常用 should + 动词原形，should 可省略。",
        "trap": "meeting 是单数，容易误选 is/was，但虚拟语气要求 be。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "What surprised us most ______ his calm attitude toward the problem.",
        "correct": "was",
        "distractors": ["were", "are", "have been"],
        "reason": "What 引导的主语从句整体作单数概念，表语为 attitude，谓语用 was。",
        "trap": "us 或 problem 不决定谓语形式，主语是整个 what 从句。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "______ he said at the meeting was quite reasonable.",
        "correct": "What",
        "distractors": ["That", "Which", "Whether"],
        "reason": "从句中 said 缺宾语，what 在主语从句中充当宾语。",
        "trap": "that 引导主语从句时不充当成分，不能填补 said 的宾语。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The fact ______ he had failed the exam surprised his parents.",
        "correct": "that",
        "distractors": ["which", "what", "whether"],
        "reason": "that 引导同位语从句，说明 fact 的具体内容。",
        "trap": "which 引导定语从句时要在从句中充当成分；本句从句成分完整。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The village ______ we spent our holiday has changed a lot.",
        "correct": "where",
        "distractors": ["which", "what", "that"],
        "reason": "先行词 village 在从句中作地点状语，应用 where。",
        "trap": "spent 后已有 our holiday 作宾语，不缺 which/that 作宾语。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The day ______ we first met is still clear in my memory.",
        "correct": "when",
        "distractors": ["which", "where", "what"],
        "reason": "先行词 day 在从句中作时间状语，应用 when。",
        "trap": "which 指物，但从句 met 不缺宾语，缺时间状语。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "This is the same book ______ I lost last week.",
        "correct": "that",
        "distractors": ["as", "what", "where"],
        "reason": "the same...that 强调就是同一本；从句 lost 缺宾语。",
        "trap": "the same...as 常表示同类，不一定是同一个，考试中要看语义。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "He has made such great progress ______ we all admire him.",
        "correct": "that",
        "distractors": ["as", "which", "what"],
        "reason": "such...that... 引导结果状语从句，表示“如此……以至于……”。",
        "trap": "such...as 可引导定语关系，但本句表达结果，且后句成分完整。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "So difficult ______ the problem that few students solved it.",
        "correct": "was",
        "distractors": ["is", "were", "has been"],
        "reason": "so + 形容词位于句首时，主句部分倒装；problem 为单数且语境为过去。",
        "trap": "few students 是复数但不是谓语主语，不能选 were。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "Only when the rain stopped ______ the match.",
        "correct": "did they continue",
        "distractors": ["they continued", "had they continued", "they had continued"],
        "reason": "Only when 位于句首，主句要部分倒装；语境为一般过去。",
        "trap": "they continued 是正常语序，但不符合 only 句首倒装。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "Seldom ______ such a moving speech.",
        "correct": "have I heard",
        "distractors": ["I have heard", "did I heard", "I heard"],
        "reason": "否定副词 seldom 位于句首时，句子部分倒装；完成时用 have I heard。",
        "trap": "did I heard 混用了助动词 did 和过去分词形式，是常见伪正确项。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "The harder you work, ______ progress you will make.",
        "correct": "the greater",
        "distractors": ["greater", "the greatest", "greatest"],
        "reason": "the + 比较级, the + 比较级 是固定结构。",
        "trap": "greater 语义上像比较级，但缺少结构中的 the。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "The room is too small ______ so many people.",
        "correct": "to hold",
        "distractors": ["holding", "held", "hold"],
        "reason": "too...to do 表示“太……而不能……”。",
        "trap": "holding 可作现在分词，但 too small 后需要不定式结构。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "He is old enough ______ the problem by himself.",
        "correct": "to solve",
        "distractors": ["solving", "solved", "solve"],
        "reason": "adj. enough to do 是固定结构。",
        "trap": "solve 是动词原形，但 enough 后通常接 to do。",
        "difficulty": 2,
    },
    {
        "submodule": "语法",
        "stem": "The question is worth ______ again.",
        "correct": "discussing",
        "distractors": ["to discuss", "discussed", "discuss"],
        "reason": "be worth doing 是固定结构，主动形式表示被动含义。",
        "trap": "to discuss 受中文“值得去讨论”影响容易误选。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "I prefer reading books ______ watching short videos.",
        "correct": "to",
        "distractors": ["than", "rather than", "instead"],
        "reason": "prefer doing A to doing B 表示“比起 B 更喜欢 A”。",
        "trap": "than 常和 would rather/better 比较结构搭配，但 prefer doing 使用 to。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "There is no point ______ about what has already happened.",
        "correct": "complaining",
        "distractors": ["to complain", "complain", "complained"],
        "reason": "There is no point doing sth. 表示“做某事没有意义”。",
        "trap": "to complain 看似可作目的，但 no point 后固定接 doing。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The task is more difficult than ______.",
        "correct": "expected",
        "distractors": ["expecting", "to expect", "expects"],
        "reason": "than expected 是省略结构，相当于 than it was expected。",
        "trap": "expecting 表主动，不能表达“被预期”。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The teacher suggested that we ______ more examples in our essays.",
        "correct": "use",
        "distractors": ["used", "uses", "will use"],
        "reason": "suggest 表示“建议”时，that 从句用 should + 动词原形，should 可省略。",
        "trap": "we 是复数也不能决定时态，关键是 suggest 后的虚拟语气。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "He suggested that the answer ______ wrong.",
        "correct": "was",
        "distractors": ["be", "were", "is being"],
        "reason": "suggest 表示“暗示、表明”时不用虚拟语气；语境为过去，故用 was。",
        "trap": "看到 suggest 容易机械选择 be，但这里不是“建议”。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "The manager demanded that the problem ______ immediately.",
        "correct": "be solved",
        "distractors": ["was solved", "is solved", "has solved"],
        "reason": "demand 后的 that 从句用 should + 动词原形，且 problem 与 solve 为被动关系。",
        "trap": "was solved 符合过去时表面形式，但不符合虚拟语气。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "The old man sat by the window, ______ the children playing outside.",
        "correct": "watching",
        "distractors": ["watched", "to watch", "watch"],
        "reason": "现在分词 watching 作伴随状语，主语 old man 与 watch 为主动关系。",
        "trap": "watched 表被动或过去，不能表达老人主动观看。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "______ from the top of the hill, the town looks beautiful.",
        "correct": "Seen",
        "distractors": ["Seeing", "To see", "See"],
        "reason": "town 与 see 是被动关系，过去分词 Seen 作条件/方式状语。",
        "trap": "Seeing 的逻辑主语应是人，但主句主语是 town，产生逻辑主语错误。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "______ the letter, he put it into an envelope.",
        "correct": "Having written",
        "distractors": ["Written", "Writing", "To write"],
        "reason": "写信发生在放入信封之前，用完成式现在分词表示先后。",
        "trap": "Writing 可表示同时进行，但不能突出先写完再装信封。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "The more he explained, ______ confused we became.",
        "correct": "the more",
        "distractors": ["more", "the most", "most"],
        "reason": "the more..., the more... 是固定比较结构。",
        "trap": "第二空也必须保留 the，不能只用 more。",
        "difficulty": 3,
    },
    {
        "submodule": "语法",
        "stem": "I don't think he is right, ______?",
        "correct": "is he",
        "distractors": ["do I", "isn't he", "don't I"],
        "reason": "I don't think... 的反意疑问通常看从句且否定转移，后面用肯定 is he。",
        "trap": "看到主句 I don't think 容易选 do I，但实际疑问针对从句 he is right。",
        "difficulty": 5,
    },
    {
        "submodule": "语法",
        "stem": "Let's discuss the problem after class, ______?",
        "correct": "shall we",
        "distractors": ["will you", "do we", "don't we"],
        "reason": "Let's... 的反意疑问句常用 shall we。",
        "trap": "祈使句常用 will you，但 Let's 包含说话人和对方，规则不同。",
        "difficulty": 4,
    },
    {
        "submodule": "语法",
        "stem": "Please close the door, ______?",
        "correct": "will you",
        "distractors": ["shall we", "do you", "won't I"],
        "reason": "普通祈使句的反意疑问可用 will you。",
        "trap": "shall we 用于 Let's，不用于普通祈使句。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— Could I borrow your notes for a day? — ______",
        "correct": "Sure, here you are.",
        "distractors": ["No, thanks.", "It doesn't matter.", "Never mind."],
        "reason": "Sure, here you are 表示同意借给对方。",
        "trap": "It doesn't matter/Never mind 常用于回应道歉，不能回应借东西请求。",
        "difficulty": 2,
    },
    {
        "submodule": "语用",
        "stem": "— Do you mind if I sit here? — ______",
        "correct": "No, go ahead.",
        "distractors": ["Yes, please.", "Never mind.", "You are welcome."],
        "reason": "回答 Do you mind...? 若同意对方坐下，应说 No, go ahead，表示“不介意”。",
        "trap": "Yes, please 看似礼貌，但 yes 表示介意，与允许对方坐下矛盾。",
        "difficulty": 4,
    },
    {
        "submodule": "语用",
        "stem": "— I'm sorry for keeping you waiting. — ______",
        "correct": "That's all right.",
        "distractors": ["With pleasure.", "Good luck.", "Congratulations."],
        "reason": "That's all right 可用于回应道歉，表示“没关系”。",
        "trap": "With pleasure 用于答应请求，不用于回应道歉。",
        "difficulty": 2,
    },
    {
        "submodule": "语用",
        "stem": "— Would you like some more tea? — ______ I have had enough.",
        "correct": "No, thanks.",
        "distractors": ["Yes, please.", "That's right.", "You're welcome."],
        "reason": "后句 I have had enough 表示已经够了，应礼貌拒绝。",
        "trap": "Yes, please 与后句语义矛盾；You're welcome 是回应感谢。",
        "difficulty": 2,
    },
    {
        "submodule": "语用",
        "stem": "— I'm going to take the entrance examination next week. — ______",
        "correct": "Good luck!",
        "distractors": ["Congratulations!", "Never mind!", "You're welcome!"],
        "reason": "考试尚未发生，应祝对方好运。",
        "trap": "Congratulations 用于已经取得成果，不能用于考前。",
        "difficulty": 2,
    },
    {
        "submodule": "语用",
        "stem": "— I have just won the first prize. — ______",
        "correct": "Congratulations!",
        "distractors": ["Good luck!", "Don't mention it!", "Take your time!"],
        "reason": "对已经获得奖项的人应表示祝贺。",
        "trap": "Good luck 用于事情发生前，不用于已经获奖。",
        "difficulty": 2,
    },
    {
        "submodule": "语用",
        "stem": "— Could you possibly explain this sentence again? — ______",
        "correct": "Of course.",
        "distractors": ["Not at all.", "It doesn't matter.", "No, I couldn't possibly."],
        "reason": "Of course 表示愿意再次解释。",
        "trap": "Not at all 常用于回应感谢或 mind 句型，不自然回应请求解释。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— The exam was much harder than I expected. — ______",
        "correct": "I know. Many students felt the same way.",
        "distractors": ["Help yourself.", "Don't mention it.", "You are welcome."],
        "reason": "对对方感受表示理解，并给出共鸣，语境自然。",
        "trap": "Help yourself 用于招待食物，不用于回应考试感受。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— Would you mind turning down the music? — ______",
        "correct": "Sorry, I'll do it right away.",
        "distractors": ["Yes, I won't.", "You're welcome.", "Good idea."],
        "reason": "对方提出降低音量的请求，礼貌回应应表示抱歉并马上处理。",
        "trap": "Yes, I won't 既不自然又逻辑混乱，是 mind 句型常见陷阱。",
        "difficulty": 4,
    },
    {
        "submodule": "语用",
        "stem": "— I can't finish the work on time. — ______",
        "correct": "Why not ask your classmates for help?",
        "distractors": ["No, I don't.", "That's all right.", "You are welcome."],
        "reason": "对方表达困难时，给出建议最合适。",
        "trap": "That's all right 用于回应道歉，不是解决困难的建议。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— Shall we meet at the library entrance? — ______",
        "correct": "That suits me fine.",
        "distractors": ["Never mind.", "Don't mention it.", "Help yourself."],
        "reason": "That suits me fine 表示时间地点安排对自己合适。",
        "trap": "Never mind/Don't mention it 都不是回应约定地点的表达。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— I forgot to bring your dictionary back. — ______ But please return it tomorrow.",
        "correct": "Never mind.",
        "distractors": ["With pleasure.", "Congratulations.", "Good luck."],
        "reason": "Never mind 可用于回应对方的小失误，表示没关系。",
        "trap": "With pleasure 用于答应帮忙，不用于回应忘记归还。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— May I ask you a personal question? — ______",
        "correct": "It depends on the question.",
        "distractors": ["You are welcome.", "Don't mention it.", "Congratulations."],
        "reason": "面对私人问题，It depends on the question 表示视问题而定，礼貌且谨慎。",
        "trap": "You are welcome 用于回应感谢，不适合回应请求提问。",
        "difficulty": 4,
    },
    {
        "submodule": "语用",
        "stem": "— I don't think I can pass the test. — ______ You still have time to review.",
        "correct": "Don't lose heart.",
        "distractors": ["Help yourself.", "It tastes good.", "You're welcome."],
        "reason": "Don't lose heart 表示“别灰心”，适合鼓励对方。",
        "trap": "Help yourself 用于招待，不用于鼓励考试焦虑的人。",
        "difficulty": 3,
    },
    {
        "submodule": "语用",
        "stem": "— Would you care for another cup of coffee? — ______",
        "correct": "No, thank you.",
        "distractors": ["I don't care.", "Never mind.", "Don't mention it."],
        "reason": "Would you care for...? 是礼貌询问是否想要，拒绝时可说 No, thank you。",
        "trap": "I don't care 字面像“不需要”，但语气很不礼貌且不符合交际场景。",
        "difficulty": 4,
    },
]


def generate_questions() -> list[dict]:
    rng = random.Random(20260504)
    existing_stems = load_existing_stems()
    questions: list[dict] = []
    seen: set[str] = set()
    for spec in SPECS:
        key = normalize_stem(spec["stem"])
        if key in existing_stems or key in seen:
            continue
        seen.add(key)
        questions.append(build_question(spec, rng))
    return questions


def write_review(questions: list[dict]) -> None:
    difficulty_counter = Counter(item["difficulty"] for item in questions)
    submodule_counter = Counter(item["submodule"] for item in questions)
    lines = [
        "# COMMON 英语运用 batch 003 大批量陷阱题质检",
        "",
        f"- 文件：`{OUTPUT_PATH.name}`",
        f"- 题量：{len(questions)}",
        "- 定位：继续扩充语言知识题库，强调近义词、形近词、固定搭配、句法结构和交际语境陷阱。",
        "- 选项策略：每题至少设置一个强干扰项，错误项尽量贴近真实误选路径。",
        "",
        "## 难度分布",
        "",
    ]
    for difficulty in sorted(difficulty_counter):
        lines.append(f"- difficulty {difficulty}: {difficulty_counter[difficulty]} 题")
    lines.extend(["", "## 子模块分布", ""])
    for submodule, count in submodule_counter.most_common():
        lines.append(f"- {submodule}: {count} 题")
    REVIEW_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    questions = generate_questions()
    if len(questions) < 100:
        raise ValueError(f"Generated too few questions: {len(questions)}")
    OUTPUT_PATH.write_text(json.dumps({"questions": questions}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_review(questions)
    print(f"Generated {len(questions)} questions")
    print(f"Wrote {OUTPUT_PATH}")
    print(f"Wrote {REVIEW_PATH}")


if __name__ == "__main__":
    main()
